### ISSUE TITLE
guys is this project dead

### ISSUE THREAD

**Issue by jbmagination** [sudocode1/boom#42]
theres been no progress since 1996 and ive been very worried about this. ive gotten no sleep because i love this boom progammin glanguuage and im very worried that its dea.d please inform me on if its dead orn ot, thank you

**Comment by sudocode1** [comment]
LMFAO

**Comment by sudocode1** [comment]
The Boom Programming language has been discontinued since late November 2020, no official updates are planned, however, feel free to create a fork to add your own elements. glow ball

**Comment by jbmagination** [comment]
![why??](https://user-images.githubusercontent.com/26027089/111920606-47c01500-8a66-11eb-944a-f5e5a6a4c69c.png)
i am very confused as to why youre laughinh at me i juts wanted ot know if this project is alive or ont

**Comment by sudocode1** [comment]
NOOOOOOOOOOOOOOOOOOOOO

**Comment by jbmagination** [comment]
HAHAHAHAH

**Comment by 1s3k3b** [comment]
Kindly stop publicly spreading misinformation about contributors of the Boom programming language (written in JavaScript). There is no proof the message seen in the above posted screenshot was actually sent by sudocode1 (aka roux).
glow ball
